/**
 * pr-builder.js
 * Takes generated code from trigger.js and:
 *   1. Creates a branch
 *   2. Commits the file
 *   3. Opens a PR
 *   4. Optionally runs gh copilot suggest for review
 *
 * Uses GitHub REST API with free GITHUB_TOKEN.
 */

const GH_API = 'https://api.github.com';

function getToken() {
  return process.env.GITHUB_TOKEN;
}

async function ghFetch(path, method = 'GET', body = null) {
  const res = await fetch(`${GH_API}${path}`, {
    method,
    headers: {
      'Authorization': `Bearer ${getToken()}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json'
    },
    body: body ? JSON.stringify(body) : undefined
  });
  if (!res.ok) throw new Error(`GitHub API ${method} ${path} → ${res.status}: ${await res.text()}`);
  return res.json();
}

/**
 * Full PR creation flow
 */
export async function buildPR({ repoOwner, repoName, branchName, commitMessage, generatedCode, issueNumber }) {
  // 1. Get default branch SHA
  const repo = await ghFetch(`/repos/${repoOwner}/${repoName}`);
  const defaultBranch = repo.default_branch;
  const branchData = await ghFetch(`/repos/${repoOwner}/${repoName}/branches/${defaultBranch}`);
  const baseSha = branchData.commit.sha;

  // 2. Create branch
  await ghFetch(`/repos/${repoOwner}/${repoName}/git/refs`, 'POST', {
    ref: `refs/heads/${branchName}`,
    sha: baseSha
  });
  console.log(`[pr-builder] Created branch: ${branchName}`);

  // 3. Parse file path from first line comment (e.g. // src/utils/helper.js)
  const firstLine = generatedCode.split('\n')[0];
  const filePathMatch = firstLine.match(/\/\/\s*(.+\.(js|ts|py|go|sh|md))/);
  const filePath = filePathMatch ? filePathMatch[1].trim() : `auto/issue-${issueNumber}.js`;

  // 4. Commit file
  const content = Buffer.from(generatedCode).toString('base64');
  await ghFetch(`/repos/${repoOwner}/${repoName}/contents/${filePath}`, 'PUT', {
    message: commitMessage,
    content,
    branch: branchName
  });
  console.log(`[pr-builder] Committed: ${filePath}`);

  // 5. Open PR
  const pr = await ghFetch(`/repos/${repoOwner}/${repoName}/pulls`, 'POST', {
    title: commitMessage,
    head: branchName,
    base: defaultBranch,
    body: `Closes #${issueNumber}\n\nAuto-generated by proxpipe pipeline.\n\n> Review with: \`gh copilot suggest\``,
    draft: false
  });
  console.log(`[pr-builder] PR opened: ${pr.html_url}`);

  return { prUrl: pr.html_url, prNumber: pr.number, filePath };
}
